# Use postgres/example user/password credentials
version: '3.9'

services:
  bot:
    depends_on:
      - db
    build: .
    restart: always
    volumes:
      - ./app:/app
    environment:
      TOKEN: value
      POSTGRES_PASSWORD: value
      TOCKEN: value


  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
